name: Sync Repository to GitLab

on:
  push:
    branches:
      - main
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Sync to GitLab
      uses: keninkujovic/gitlab-sync@2.1.0
      with:
        gitlab_url: ${{ secrets.GITLAB_URL }}
        username: ${{ secrets.USER_NAME }}
        gitlab_pat: ${{ secrets.GITLAB_PAT }}
