name: Deploy Documentation

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PKG_NAME: a_test_pkg

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints sphinx-copybutton

      - name: Create VERSION file
        run: echo "${GITHUB_REF##*/}" > "${PKG_NAME}/VERSION"  # Use the environment variable

      - name: Generate API documentation
        run: |
          sphinx-apidoc -o docs "${PKG_NAME}/" --module-first --force --separate --templatedir docs/_templates
          sphinx-build -b html docs public

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: public
